/* generated by embed-schemas.mjs — do not edit by hand */
export const SCHEMA_DATA = {
  "rules": {
    "protocolVersion": 2,
    "minProtocolVersion": 1,
    "maxProtocolVersion": 2,
    "maxEnvelopeBytes": 65536,
    "suggestedRawChunkBytes": 32768,
    "maxSnapshotBytes": 2097152,
    "maxReconcileItems": 32,
    "maxChunkCount": 128,
    "maxAssemblerSessions": 16,
    "occurredAtSubset": "UTC RFC3339: YYYY-MM-DDTHH:MM:SSZ or YYYY-MM-DDTHH:MM:SS.fractionZ with a real calendar date and clock; Z only, no numeric offsets.",
    "identityForbidden": [
      "health",
      "handshake",
      "ai.complete",
      "ui.open"
    ],
    "identityRequired": [
      "application.queryCandidates",
      "job.save",
      "fill.submit",
      "snapshot.chunk",
      "submit.confirm",
      "outbox.reconcile",
      "resume.read",
      "resume.update",
      "legacy.import"
    ],
    "writeTypes": [
      "job.save",
      "fill.submit",
      "snapshot.chunk",
      "submit.confirm"
    ],
    "messageTypes": [
      "health",
      "handshake",
      "application.queryCandidates",
      "job.save",
      "fill.submit",
      "snapshot.chunk",
      "submit.confirm",
      "outbox.reconcile",
      "resume.read",
      "resume.update",
      "ai.complete",
      "ui.open",
      "legacy.import"
    ],
    "v2MessageTypes": [
      "resume.read",
      "resume.update",
      "ai.complete",
      "ui.open",
      "legacy.import"
    ],
    "errorCodes": [
      "identity_missing",
      "identity_not_allowed",
      "restore_epoch_mismatch",
      "protocol_incompatible",
      "unknown_message_type",
      "invalid_payload",
      "payload_too_large",
      "conflict",
      "previously_purged",
      "unavailable",
      "secret_forbidden"
    ],
    "reconcileStatuses": [
      "applied",
      "purged",
      "not_found",
      "conflict",
      "unverifiable"
    ],
    "retryableErrorCodes": [
      "unavailable"
    ],
    "urlSecretQueryKeys": [
      "token",
      "access_token",
      "refresh_token",
      "id_token",
      "session",
      "sessionid",
      "sid",
      "auth",
      "authorization",
      "api_key",
      "apikey",
      "password",
      "pwd",
      "secret",
      "signature",
      "sig",
      "code",
      "key"
    ],
    "urlAllowlist": [],
    "saveIntentIsNotMessageType": true,
    "notes": {
      "size": "Limit is the UTF-8 byte length of the complete serialized business envelope, excluding the Native Messaging 4-byte length prefix.",
      "identity": "Schema cannot prove an envelope matches the desktop current pointer. After structural validation, D03/D06 must compare archiveId/restoreEpoch to current.json.",
      "sourceRestoreEpoch": "Bound at pairing/bind time and immutable. Never overwrite with the current epoch.",
      "reconcile": "Read-only. A successful reconcile item does not authorize replay or rewrite of the old envelope."
    }
  },
  "envelope": {
    "$id": "https://resumepro.local/protocol/request-envelope.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Resume Pro request envelope",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "protocolVersion",
      "messageId",
      "clientInstanceId",
      "messageType",
      "occurredAt",
      "payload"
    ],
    "properties": {
      "protocolVersion": {
        "type": "integer",
        "minimum": 1
      },
      "messageId": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "clientInstanceId": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "messageType": {
        "type": "string",
        "enum": [
          "health",
          "handshake",
          "application.queryCandidates",
          "job.save",
          "fill.submit",
          "snapshot.chunk",
          "submit.confirm",
          "outbox.reconcile",
          "resume.read",
          "resume.update",
          "ai.complete",
          "ui.open",
          "legacy.import"
        ]
      },
      "occurredAt": {
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$",
        "description": "UTC RFC3339 subset: YYYY-MM-DDTHH:MM:SSZ or YYYY-MM-DDTHH:MM:SS.fractionZ. Pattern is syntactic; validators also reject impossible dates/times. No timezone offset other than Z."
      },
      "archiveId": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "restoreEpoch": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "payload": {
        "type": "object"
      }
    }
  },
  "response": {
    "$id": "https://resumepro.local/protocol/response-envelope.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Resume Pro response envelope",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "protocolVersion",
      "correlationId",
      "ok",
      "payload"
    ],
    "properties": {
      "protocolVersion": {
        "type": "integer",
        "minimum": 1
      },
      "correlationId": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "resultId": {
        "type": "string",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "ok": {
        "type": "boolean"
      },
      "error": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "code",
          "retryable"
        ],
        "properties": {
          "code": {
            "type": "string",
            "enum": [
              "identity_missing",
              "identity_not_allowed",
              "restore_epoch_mismatch",
              "protocol_incompatible",
              "unknown_message_type",
              "invalid_payload",
              "payload_too_large",
              "conflict",
              "previously_purged",
              "unavailable",
              "secret_forbidden"
            ]
          },
          "retryable": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "maxLength": 300
          }
        }
      },
      "payload": {
        "type": "object"
      }
    }
  },
  "payloads": {
    "ai-complete": {
      "$id": "https://resumepro.local/protocol/payloads/ai-complete.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "purpose",
        "system",
        "user"
      ],
      "properties": {
        "purpose": {
          "type": "string",
          "enum": [
            "fill",
            "plan"
          ]
        },
        "system": {
          "type": "string",
          "maxLength": 8000
        },
        "user": {
          "type": "string",
          "maxLength": 60000
        }
      }
    },
    "fill-submit": {
      "$id": "https://resumepro.local/protocol/payloads/fill-submit.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sourceRestoreEpoch",
        "payloadSha256",
        "applicationId",
        "outcome"
      ],
      "properties": {
        "sourceRestoreEpoch": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "payloadSha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "applicationId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "outcome": {
          "type": "string",
          "enum": [
            "started",
            "completed",
            "partial",
            "failed",
            "cancelled"
          ]
        },
        "fieldCount": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "filledCount": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "unconfirmedCount": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "durationsMs": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scan": {
              "type": "integer",
              "minimum": 0,
              "maximum": 3600000
            },
            "match": {
              "type": "integer",
              "minimum": 0,
              "maximum": 3600000
            },
            "fill": {
              "type": "integer",
              "minimum": 0,
              "maximum": 3600000
            },
            "total": {
              "type": "integer",
              "minimum": 0,
              "maximum": 3600000
            }
          }
        },
        "urlRedacted": {
          "type": "string",
          "maxLength": 2000
        },
        "templateName": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "templateVersion": {
          "type": "string",
          "maxLength": 64
        },
        "snapshotId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "sha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "pluginVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        }
      }
    },
    "handshake": {
      "$id": "https://resumepro.local/protocol/payloads/handshake.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "pluginVersion",
        "minProtocolVersion",
        "maxProtocolVersion"
      ],
      "properties": {
        "pluginVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "minProtocolVersion": {
          "type": "integer",
          "minimum": 1
        },
        "maxProtocolVersion": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "health": {
      "$id": "https://resumepro.local/protocol/payloads/health.json",
      "type": "object",
      "additionalProperties": false,
      "properties": {}
    },
    "job-save": {
      "$id": "https://resumepro.local/protocol/payloads/job-save.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sourceRestoreEpoch",
        "payloadSha256",
        "company",
        "title"
      ],
      "properties": {
        "sourceRestoreEpoch": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "payloadSha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "company": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "sourceUrl": {
          "type": "string",
          "maxLength": 2000
        },
        "location": {
          "type": "string"
        },
        "applicationId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        }
      }
    },
    "legacy-import": {
      "$id": "https://resumepro.local/protocol/payloads/legacy-import.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "importId",
        "kind"
      ],
      "properties": {
        "importId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "kind": {
          "type": "string",
          "enum": [
            "manifest",
            "template",
            "profile",
            "aiConfig",
            "status"
          ]
        },
        "index": {
          "type": "integer",
          "minimum": 0,
          "maximum": 63
        },
        "body": {
          "type": "object"
        }
      },
      "$defs": {
        "manifest": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "pluginVersion",
            "total",
            "parts"
          ],
          "properties": {
            "pluginVersion": {
              "type": "string",
              "minLength": 1,
              "maxLength": 64
            },
            "total": {
              "type": "integer",
              "minimum": 1,
              "maximum": 63
            },
            "parts": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "index",
                  "kind",
                  "sha256"
                ],
                "properties": {
                  "index": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 63
                  },
                  "kind": {
                    "type": "string",
                    "enum": [
                      "template",
                      "profile",
                      "aiConfig"
                    ]
                  },
                  "sha256": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{64}$"
                  }
                }
              },
              "minItems": 1,
              "maxItems": 63
            }
          }
        },
        "template": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "name",
            "wasActive",
            "groups"
          ],
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1,
              "maxLength": 100
            },
            "wasActive": {
              "type": "boolean"
            },
            "groups": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "name",
                  "fields"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "fields": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "key",
                        "value"
                      ],
                      "properties": {
                        "key": {
                          "type": "string",
                          "minLength": 1
                        },
                        "value": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "profile": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "values",
            "family",
            "custom"
          ],
          "properties": {
            "values": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "family": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              }
            },
            "custom": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "key",
                  "value"
                ],
                "properties": {
                  "key": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                }
              },
              "maxItems": 200
            }
          }
        },
        "aiConfig": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "apiUrl",
            "model",
            "apiKey"
          ],
          "properties": {
            "apiUrl": {
              "type": "string",
              "minLength": 1,
              "maxLength": 2000
            },
            "model": {
              "type": "string",
              "minLength": 1,
              "maxLength": 200
            },
            "apiKey": {
              "type": "string",
              "minLength": 1,
              "maxLength": 4096
            }
          }
        }
      }
    },
    "outbox-reconcile": {
      "$id": "https://resumepro.local/protocol/payloads/outbox-reconcile.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "items"
      ],
      "properties": {
        "items": {
          "type": "array",
          "minItems": 1,
          "maxItems": 32,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "clientInstanceId",
              "messageId",
              "sourceRestoreEpoch",
              "payloadSha256"
            ],
            "properties": {
              "clientInstanceId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "messageId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "sourceRestoreEpoch": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "payloadSha256": {
                "type": "string",
                "pattern": "^[0-9a-f]{64}$"
              },
              "snapshotId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "chunkIndex": {
                "type": "integer",
                "minimum": 0,
                "maximum": 127
              }
            }
          }
        }
      }
    },
    "query-candidates": {
      "$id": "https://resumepro.local/protocol/payloads/query-candidates.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "company"
      ],
      "properties": {
        "company": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "title": {
          "type": "string",
          "maxLength": 200
        },
        "sourceUrl": {
          "type": "string",
          "maxLength": 2000
        }
      }
    },
    "resume-read": {
      "$id": "https://resumepro.local/protocol/payloads/resume-read.json",
      "type": "object",
      "additionalProperties": false,
      "required": [],
      "properties": {}
    },
    "resume-update": {
      "$id": "https://resumepro.local/protocol/payloads/resume-update.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "op"
      ],
      "properties": {
        "op": {
          "type": "string",
          "enum": [
            "setActiveTemplate",
            "saveProfile"
          ]
        },
        "templateId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "profile": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "values",
            "family",
            "custom"
          ],
          "properties": {
            "values": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "family": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              }
            },
            "custom": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "key",
                  "value"
                ],
                "properties": {
                  "key": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                }
              },
              "maxItems": 200
            }
          }
        },
        "expectedRevision": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "snapshot-chunk": {
      "$id": "https://resumepro.local/protocol/payloads/snapshot-chunk.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sourceRestoreEpoch",
        "snapshotId",
        "applicationId",
        "chunkIndex",
        "chunkCount",
        "chunkSha256",
        "snapshotSha256",
        "byteSize",
        "bytesBase64"
      ],
      "properties": {
        "sourceRestoreEpoch": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "snapshotId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "applicationId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "chunkIndex": {
          "type": "integer",
          "minimum": 0,
          "maximum": 127
        },
        "chunkCount": {
          "type": "integer",
          "minimum": 1,
          "maximum": 128
        },
        "chunkSha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "snapshotSha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "byteSize": {
          "type": "integer",
          "minimum": 1,
          "maximum": 2097152
        },
        "bytesBase64": {
          "type": "string",
          "minLength": 1,
          "maxLength": 65536
        }
      }
    },
    "submit-confirm": {
      "$id": "https://resumepro.local/protocol/payloads/submit-confirm.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sourceRestoreEpoch",
        "payloadSha256",
        "applicationId"
      ],
      "properties": {
        "sourceRestoreEpoch": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "payloadSha256": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        },
        "applicationId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        }
      }
    },
    "ui-open": {
      "$id": "https://resumepro.local/protocol/payloads/ui-open.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "view"
      ],
      "properties": {
        "view": {
          "type": "string",
          "enum": [
            "resume",
            "settings-ai",
            "home"
          ]
        }
      }
    }
  },
  "responses": {
    "ai-complete": {
      "$id": "https://resumepro.local/protocol/responses/ai-complete.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status"
      ],
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "ok",
            "failed"
          ]
        },
        "text": {
          "type": "string"
        },
        "reason": {
          "type": "string",
          "enum": [
            "not_configured",
            "auth",
            "rate_limited",
            "timeout",
            "network",
            "http",
            "bad_response",
            "input_too_large",
            "response_too_large"
          ]
        },
        "httpStatus": {
          "type": "integer",
          "minimum": 100,
          "maximum": 599
        },
        "host": {
          "type": "string",
          "maxLength": 253
        }
      }
    },
    "handshake": {
      "$id": "https://resumepro.local/protocol/responses/handshake.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "appVersion",
        "minProtocolVersion",
        "maxProtocolVersion",
        "archiveId",
        "restoreEpoch",
        "capabilities"
      ],
      "properties": {
        "appVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "minProtocolVersion": {
          "type": "integer",
          "minimum": 1
        },
        "maxProtocolVersion": {
          "type": "integer",
          "minimum": 1
        },
        "archiveId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "restoreEpoch": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "capabilities": {
          "type": "array",
          "minItems": 1,
          "maxItems": 16,
          "items": {
            "type": "string",
            "enum": [
              "health",
              "handshake",
              "application.queryCandidates",
              "job.save",
              "fill.submit",
              "snapshot.chunk",
              "submit.confirm",
              "outbox.reconcile"
            ]
          }
        }
      }
    },
    "health": {
      "$id": "https://resumepro.local/protocol/responses/health.json",
      "type": "object",
      "additionalProperties": false,
      "properties": {}
    },
    "legacy-import": {
      "$id": "https://resumepro.local/protocol/responses/legacy-import.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "state",
        "received",
        "total"
      ],
      "properties": {
        "state": {
          "type": "string",
          "enum": [
            "receiving",
            "awaiting_confirmation",
            "imported",
            "rejected",
            "expired"
          ]
        },
        "received": {
          "type": "integer",
          "minimum": 0,
          "maximum": 63
        },
        "total": {
          "type": "integer",
          "minimum": 1,
          "maximum": 63
        }
      }
    },
    "outbox-reconcile": {
      "$id": "https://resumepro.local/protocol/responses/outbox-reconcile.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "items"
      ],
      "properties": {
        "items": {
          "type": "array",
          "minItems": 1,
          "maxItems": 32,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "clientInstanceId",
              "messageId",
              "sourceRestoreEpoch",
              "payloadSha256",
              "status"
            ],
            "properties": {
              "clientInstanceId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "messageId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "sourceRestoreEpoch": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "payloadSha256": {
                "type": "string",
                "pattern": "^[0-9a-f]{64}$"
              },
              "status": {
                "type": "string",
                "enum": [
                  "applied",
                  "purged",
                  "not_found",
                  "conflict",
                  "unverifiable"
                ]
              },
              "resultId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "snapshotId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "chunkIndex": {
                "type": "integer",
                "minimum": 0
              }
            }
          }
        }
      }
    },
    "query-candidates": {
      "$id": "https://resumepro.local/protocol/responses/query-candidates.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "exact",
        "sameCompany"
      ],
      "properties": {
        "exact": {
          "type": "array",
          "maxItems": 32,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "applicationId",
              "company",
              "title"
            ],
            "properties": {
              "applicationId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "company": {
                "type": "string",
                "minLength": 1,
                "maxLength": 200
              },
              "title": {
                "type": "string",
                "minLength": 1,
                "maxLength": 200
              },
              "stage": {
                "type": "string",
                "maxLength": 32
              },
              "sourceUrl": {
                "type": "string",
                "maxLength": 2000
              },
              "updatedAt": {
                "type": "string",
                "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"
              }
            }
          }
        },
        "sameCompany": {
          "type": "array",
          "maxItems": 32,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "applicationId",
              "company",
              "title"
            ],
            "properties": {
              "applicationId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "company": {
                "type": "string",
                "minLength": 1,
                "maxLength": 200
              },
              "title": {
                "type": "string",
                "minLength": 1,
                "maxLength": 200
              },
              "stage": {
                "type": "string",
                "maxLength": 32
              },
              "sourceUrl": {
                "type": "string",
                "maxLength": 2000
              },
              "updatedAt": {
                "type": "string",
                "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"
              }
            }
          }
        }
      }
    },
    "resume-read": {
      "$id": "https://resumepro.local/protocol/responses/resume-read.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "templates",
        "activeTemplate",
        "profile",
        "profileRevision"
      ],
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "id",
              "name",
              "fieldCount"
            ],
            "properties": {
              "id": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
              },
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100
              },
              "fieldCount": {
                "type": "integer",
                "minimum": 0
              }
            }
          },
          "maxItems": 25
        },
        "activeTemplate": {
          "type": [
            "object",
            "null"
          ],
          "additionalProperties": false,
          "required": [
            "id",
            "name",
            "groups"
          ],
          "properties": {
            "id": {
              "type": "string",
              "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
            },
            "name": {
              "type": "string",
              "minLength": 1,
              "maxLength": 100
            },
            "groups": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "name",
                  "fields"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "fields": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "key",
                        "value"
                      ],
                      "properties": {
                        "key": {
                          "type": "string",
                          "minLength": 1
                        },
                        "value": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "profile": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "values",
            "family",
            "custom"
          ],
          "properties": {
            "values": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "family": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              }
            },
            "custom": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "key",
                  "value"
                ],
                "properties": {
                  "key": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                }
              },
              "maxItems": 200
            }
          }
        },
        "profileRevision": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "resume-update": {
      "$id": "https://resumepro.local/protocol/responses/resume-update.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "activeTemplateId",
        "profileRevision"
      ],
      "properties": {
        "activeTemplateId": {
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "profileRevision": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "snapshot-chunk": {
      "$id": "https://resumepro.local/protocol/responses/snapshot-chunk.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ackKind",
        "chunkIndex",
        "chunkCursor"
      ],
      "properties": {
        "ackKind": {
          "type": "string",
          "enum": [
            "chunk",
            "snapshot"
          ]
        },
        "chunkIndex": {
          "type": "integer",
          "minimum": 0,
          "maximum": 127
        },
        "chunkCursor": {
          "type": "integer",
          "minimum": 0,
          "maximum": 128
        },
        "snapshotId": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        }
      }
    },
    "ui-open": {
      "$id": "https://resumepro.local/protocol/responses/ui-open.json",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "opened"
      ],
      "properties": {
        "opened": {
          "type": "boolean",
          "enum": [
            true
          ]
        }
      }
    },
    "write": {
      "$id": "https://resumepro.local/protocol/responses/write.json",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resultKind": {
          "type": "string",
          "maxLength": 64
        }
      }
    }
  }
};
