/* generated by gen-types.mjs — do not edit by hand */
/* Source of truth: desktop/crates/protocol/schemas/. Regenerate with:
   node desktop/crates/protocol/js/gen-types.mjs */

export type MessageType =
  | "health"
  | "handshake"
  | "application.queryCandidates"
  | "job.save"
  | "fill.submit"
  | "snapshot.chunk"
  | "submit.confirm"
  | "outbox.reconcile"
  | "resume.read"
  | "resume.update"
  | "ai.complete"
  | "ui.open"
  | "legacy.import";

/** Resume Pro request envelope */
export interface RequestEnvelope {
  /** minimum: 1 */
  protocolVersion: number;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  messageId: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  clientInstanceId: string;
  messageType: "health" | "handshake" | "application.queryCandidates" | "job.save" | "fill.submit" | "snapshot.chunk" | "submit.confirm" | "outbox.reconcile" | "resume.read" | "resume.update" | "ai.complete" | "ui.open" | "legacy.import";
  /**
   * UTC RFC3339 subset: YYYY-MM-DDTHH:MM:SSZ or YYYY-MM-DDTHH:MM:SS.fractionZ. Pattern is syntactic; validators also reject impossible dates/times. No timezone offset other than Z.
   * pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$
   */
  occurredAt: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  archiveId?: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  restoreEpoch?: string;
  payload: Record<string, unknown>;
}

/** Resume Pro response envelope */
export interface ResponseEnvelope {
  /** minimum: 1 */
  protocolVersion: number;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  correlationId: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  resultId?: string;
  ok: boolean;
  error?: {
    code: "identity_missing" | "identity_not_allowed" | "restore_epoch_mismatch" | "protocol_incompatible" | "unknown_message_type" | "invalid_payload" | "payload_too_large" | "conflict" | "previously_purged" | "unavailable" | "secret_forbidden";
    retryable: boolean;
    /** maxLength: 300 */
    message?: string;
  };
  payload: Record<string, unknown>;
}

export interface AiCompletePayload {
  purpose: "fill" | "plan";
  /** maxLength: 8000 */
  system: string;
  /** maxLength: 60000 */
  user: string;
}

export interface FillSubmitPayload {
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  sourceRestoreEpoch: string;
  /** pattern: ^[0-9a-f]{64}$ */
  payloadSha256: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  applicationId: string;
  outcome: "started" | "completed" | "partial" | "failed" | "cancelled";
  /**
   * minimum: 0
   * maximum: 10000
   */
  fieldCount?: number;
  /**
   * minimum: 0
   * maximum: 10000
   */
  filledCount?: number;
  /**
   * minimum: 0
   * maximum: 10000
   */
  unconfirmedCount?: number;
  durationsMs?: {
    /**
     * minimum: 0
     * maximum: 3600000
     */
    scan?: number;
    /**
     * minimum: 0
     * maximum: 3600000
     */
    match?: number;
    /**
     * minimum: 0
     * maximum: 3600000
     */
    fill?: number;
    /**
     * minimum: 0
     * maximum: 3600000
     */
    total?: number;
  };
  /** maxLength: 2000 */
  urlRedacted?: string;
  /**
   * minLength: 1
   * maxLength: 200
   */
  templateName?: string;
  /** maxLength: 64 */
  templateVersion?: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  snapshotId?: string;
  /** pattern: ^[0-9a-f]{64}$ */
  sha256?: string;
  /**
   * minLength: 1
   * maxLength: 64
   */
  pluginVersion?: string;
}

export interface HandshakePayload {
  /**
   * minLength: 1
   * maxLength: 64
   */
  pluginVersion: string;
  /** minimum: 1 */
  minProtocolVersion: number;
  /** minimum: 1 */
  maxProtocolVersion: number;
}

export interface HealthPayload {
}

export interface JobSavePayload {
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  sourceRestoreEpoch: string;
  /** pattern: ^[0-9a-f]{64}$ */
  payloadSha256: string;
  /**
   * minLength: 1
   * maxLength: 200
   */
  company: string;
  /**
   * minLength: 1
   * maxLength: 200
   */
  title: string;
  /** maxLength: 2000 */
  sourceUrl?: string;
  location?: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  applicationId?: string;
}

export interface LegacyImportPayload {
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  importId: string;
  kind: "manifest" | "template" | "profile" | "aiConfig" | "status";
  /**
   * minimum: 0
   * maximum: 63
   */
  index?: number;
  body?: Record<string, unknown>;
}

export interface OutboxReconcilePayload {
  /**
   * minItems: 1
   * maxItems: 32
   */
  items: {
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    clientInstanceId: string;
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    messageId: string;
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    sourceRestoreEpoch: string;
    /** pattern: ^[0-9a-f]{64}$ */
    payloadSha256: string;
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    snapshotId?: string;
    /**
     * minimum: 0
     * maximum: 127
     */
    chunkIndex?: number;
  }[];
}

export interface QueryCandidatesPayload {
  /**
   * minLength: 1
   * maxLength: 200
   */
  company: string;
  /** maxLength: 200 */
  title?: string;
  /** maxLength: 2000 */
  sourceUrl?: string;
}

export interface ResumeReadPayload {
}

export interface ResumeUpdatePayload {
  op: "setActiveTemplate" | "saveProfile";
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  templateId?: string;
  profile?: {
    values: Record<string, string>;
    family: Record<string, string>[];
    /** maxItems: 200 */
    custom: {
      key: string;
      value: string;
    }[];
  };
  /** minimum: 0 */
  expectedRevision?: number;
}

export interface SnapshotChunkPayload {
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  sourceRestoreEpoch: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  snapshotId: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  applicationId: string;
  /**
   * minimum: 0
   * maximum: 127
   */
  chunkIndex: number;
  /**
   * minimum: 1
   * maximum: 128
   */
  chunkCount: number;
  /** pattern: ^[0-9a-f]{64}$ */
  chunkSha256: string;
  /** pattern: ^[0-9a-f]{64}$ */
  snapshotSha256: string;
  /**
   * minimum: 1
   * maximum: 2097152
   */
  byteSize: number;
  /**
   * minLength: 1
   * maxLength: 65536
   */
  bytesBase64: string;
}

export interface SubmitConfirmPayload {
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  sourceRestoreEpoch: string;
  /** pattern: ^[0-9a-f]{64}$ */
  payloadSha256: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  applicationId: string;
}

export interface UiOpenPayload {
  view: "resume" | "settings-ai" | "home";
}

export interface AiCompleteResponsePayload {
  status: "ok" | "failed";
  text?: string;
  reason?: "not_configured" | "credential_unavailable" | "auth" | "rate_limited" | "timeout" | "network" | "http" | "bad_response" | "input_too_large" | "response_too_large";
  /**
   * minimum: 100
   * maximum: 599
   */
  httpStatus?: number;
  /** maxLength: 253 */
  host?: string;
}

export interface HandshakeResponsePayload {
  /**
   * minLength: 1
   * maxLength: 64
   */
  appVersion: string;
  /** minimum: 1 */
  minProtocolVersion: number;
  /** minimum: 1 */
  maxProtocolVersion: number;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  archiveId: string;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  restoreEpoch: string;
  /**
   * minItems: 1
   * maxItems: 16
   */
  capabilities: ("health" | "handshake" | "application.queryCandidates" | "job.save" | "fill.submit" | "snapshot.chunk" | "submit.confirm" | "outbox.reconcile" | "resume.read" | "resume.update" | "ai.complete" | "ui.open" | "legacy.import")[];
}

export interface HealthResponsePayload {
}

export interface LegacyImportResponsePayload {
  state: "receiving" | "awaiting_confirmation" | "imported" | "rejected" | "expired";
  /**
   * minimum: 0
   * maximum: 63
   */
  received: number;
  /**
   * minimum: 1
   * maximum: 63
   */
  total: number;
}

export interface OutboxReconcileResponsePayload {
  /**
   * minItems: 1
   * maxItems: 32
   */
  items: {
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    clientInstanceId: string;
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    messageId: string;
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    sourceRestoreEpoch: string;
    /** pattern: ^[0-9a-f]{64}$ */
    payloadSha256: string;
    status: "applied" | "purged" | "not_found" | "conflict" | "unverifiable";
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    resultId?: string;
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    snapshotId?: string;
    /** minimum: 0 */
    chunkIndex?: number;
  }[];
}

export interface QueryCandidatesResponsePayload {
  /** maxItems: 32 */
  exact: {
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    applicationId: string;
    /**
     * minLength: 1
     * maxLength: 200
     */
    company: string;
    /**
     * minLength: 1
     * maxLength: 200
     */
    title: string;
    /** maxLength: 32 */
    stage?: string;
    /** maxLength: 2000 */
    sourceUrl?: string;
    /** pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$ */
    updatedAt?: string;
  }[];
  /** maxItems: 32 */
  sameCompany: {
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    applicationId: string;
    /**
     * minLength: 1
     * maxLength: 200
     */
    company: string;
    /**
     * minLength: 1
     * maxLength: 200
     */
    title: string;
    /** maxLength: 32 */
    stage?: string;
    /** maxLength: 2000 */
    sourceUrl?: string;
    /** pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$ */
    updatedAt?: string;
  }[];
}

export interface ResumeReadResponsePayload {
  /** maxItems: 25 */
  templates: {
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    id: string;
    /**
     * minLength: 1
     * maxLength: 100
     */
    name: string;
    /** minimum: 0 */
    fieldCount: number;
  }[];
  activeTemplate: {
    /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
    id: string;
    /**
     * minLength: 1
     * maxLength: 100
     */
    name: string;
    groups: {
      /** minLength: 1 */
      name: string;
      fields: {
        /** minLength: 1 */
        key: string;
        value: string;
      }[];
    }[];
  } | null;
  profile: {
    values: Record<string, string>;
    family: Record<string, string>[];
    /** maxItems: 200 */
    custom: {
      key: string;
      value: string;
    }[];
  };
  /** minimum: 0 */
  profileRevision: number;
}

export interface ResumeUpdateResponsePayload {
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  activeTemplateId: string | null;
  /** minimum: 0 */
  profileRevision: number;
}

export interface SnapshotChunkResponsePayload {
  ackKind: "chunk" | "snapshot";
  /**
   * minimum: 0
   * maximum: 127
   */
  chunkIndex: number;
  /**
   * minimum: 0
   * maximum: 128
   */
  chunkCursor: number;
  /** pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ */
  snapshotId?: string;
}

export interface UiOpenResponsePayload {
  opened: true;
}

export interface WriteResponsePayload {
  /** maxLength: 64 */
  resultKind?: string;
}

/** Request payload type for a given messageType. */
export interface RequestPayloadByType {
  "health": HealthPayload;
  "handshake": HandshakePayload;
  "application.queryCandidates": QueryCandidatesPayload;
  "job.save": JobSavePayload;
  "fill.submit": FillSubmitPayload;
  "snapshot.chunk": SnapshotChunkPayload;
  "submit.confirm": SubmitConfirmPayload;
  "outbox.reconcile": OutboxReconcilePayload;
  "resume.read": ResumeReadPayload;
  "resume.update": ResumeUpdatePayload;
  "ai.complete": AiCompletePayload;
  "ui.open": UiOpenPayload;
  "legacy.import": LegacyImportPayload;
}

/** Response payload type for a given messageType. Several writes share one response. */
export interface ResponsePayloadByType {
  "health": HealthResponsePayload;
  "handshake": HandshakeResponsePayload;
  "application.queryCandidates": QueryCandidatesResponsePayload;
  "job.save": WriteResponsePayload;
  "fill.submit": WriteResponsePayload;
  "snapshot.chunk": SnapshotChunkResponsePayload;
  "submit.confirm": WriteResponsePayload;
  "outbox.reconcile": OutboxReconcileResponsePayload;
  "resume.read": ResumeReadResponsePayload;
  "resume.update": ResumeUpdateResponsePayload;
  "ai.complete": AiCompleteResponsePayload;
  "ui.open": UiOpenResponsePayload;
  "legacy.import": LegacyImportResponsePayload;
}

/** One request envelope, narrowed to the payload its messageType carries. */
export type RequestFor<T extends MessageType> = Omit<RequestEnvelope, "messageType" | "payload"> & {
  messageType: T;
  payload: RequestPayloadByType[T];
};

/** A successful response, narrowed to the payload the request's messageType expects. */
export type ResponseFor<T extends MessageType> = Omit<ResponseEnvelope, "payload"> & {
  ok: true;
  payload: ResponsePayloadByType[T];
};
