import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { desktopVersion, packageVersion } from "./check-desktop-release.js";
import {
  applyVersion,
  setCargoLockVersion,
  setCargoTomlVersion,
  setTauriConfVersion,
} from "./set-version.js";

const here = dirname(fileURLToPath(import.meta.url));
const tauriDir = resolve(here, "..", "src-tauri");

const crlf = (text) => text.split("\n").join("\r\n");
const hasBareLf = (text) => text.split("\r\n").join("").includes("\n");

const CONF = `{
  "productName": "Resume Pro Desktop",
  "version": "0.1.0",
  "plugins": { "updater": { "version": "9.9.9" } }
}
`;

const TOML = `[package]
name = "resume-pro-desktop"
version = "0.1.0"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.regex]
version = "1.10.0"
`;

const LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "other-crate"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "resume-pro-desktop"
version = "0.1.0"
dependencies = [
 "other-crate",
]

[[package]]
name = "zeta"
version = "0.1.0"
`;

test("tauri.conf.json 只改顶层 version，别处同名字段和其余字节都不动", () => {
  const out = setTauriConfVersion(CONF, "0.1.0-beta.2");
  assert.equal(JSON.parse(out).version, "0.1.0-beta.2");
  assert.equal(JSON.parse(out).plugins.updater.version, "9.9.9");
  assert.equal(out, CONF.replace('"version": "0.1.0"', '"version": "0.1.0-beta.2"'));
});

test("Cargo.toml 只改 [package] 段，依赖项的 version 不动", () => {
  const out = setCargoTomlVersion(TOML, "0.1.0-beta.2");
  assert.equal(packageVersion(out), "0.1.0-beta.2");
  assert.equal(out, TOML.replace('name = "resume-pro-desktop"\nversion = "0.1.0"', 'name = "resume-pro-desktop"\nversion = "0.1.0-beta.2"'));
});

test("Cargo.lock 只改本应用那一条，版本号相同的别的包不动", () => {
  const out = setCargoLockVersion(LOCK, "resume-pro-desktop", "0.1.0-beta.2");
  assert.equal(
    out,
    LOCK.replace(
      'name = "resume-pro-desktop"\nversion = "0.1.0"',
      'name = "resume-pro-desktop"\nversion = "0.1.0-beta.2"',
    ),
  );
});

test("Cargo.lock 里找不到这个包，或者出现不止一次，都要报错而不是悄悄不改", () => {
  assert.throws(() => setCargoLockVersion(LOCK, "no-such-crate", "0.1.0-beta.1"), /找不到|没有/);
  const twice = `${LOCK}\n[[package]]\nname = "resume-pro-desktop"\nversion = "0.2.0"\n`;
  assert.throws(() => setCargoLockVersion(twice, "resume-pro-desktop", "0.1.0-beta.1"), /不止一/);
});

test("CRLF 的文件改完仍然是 CRLF，不会整份文件的换行都变掉", () => {
  assert.equal(hasBareLf(setTauriConfVersion(crlf(CONF), "0.1.0-beta.2")), false);
  assert.equal(hasBareLf(setCargoTomlVersion(crlf(TOML), "0.1.0-beta.2")), false);
  assert.equal(hasBareLf(setCargoLockVersion(crlf(LOCK), "resume-pro-desktop", "0.1.0-beta.2")), false);
});

test("不合规的版本号一律拒绝，改之前就拦下", () => {
  for (const bad of ["0.1", "0.1.0-rc.1", "0.1.0-beta", "0.1.0-beta.0", "1.2.3+build", ""]) {
    assert.throws(() => setTauriConfVersion(CONF, bad), /1\.2\.3/, `tauri.conf: ${bad}`);
    assert.throws(() => setCargoTomlVersion(TOML, bad), /1\.2\.3/, `Cargo.toml: ${bad}`);
    assert.throws(() => setCargoLockVersion(LOCK, "resume-pro-desktop", bad), /1\.2\.3/, `Cargo.lock: ${bad}`);
  }
});

test("在仓库真实文件的副本上改：三处读出来一致，改回去逐字节和原来一样", () => {
  const root = mkdtempSync(join(tmpdir(), "set-version-"));
  const dir = join(root, "desktop", "src-tauri");
  mkdirSync(dir, { recursive: true });
  const names = ["tauri.conf.json", "Cargo.toml", "Cargo.lock"];
  const original = Object.fromEntries(names.map((n) => [n, readFileSync(join(tauriDir, n), "utf8")]));
  for (const n of names) writeFileSync(join(dir, n), original[n]);

  const before = desktopVersion({ tauriConf: original["tauri.conf.json"], cargoToml: original["Cargo.toml"] });
  applyVersion(root, "0.9.9-beta.4");

  const conf = readFileSync(join(dir, "tauri.conf.json"), "utf8");
  const toml = readFileSync(join(dir, "Cargo.toml"), "utf8");
  const lock = readFileSync(join(dir, "Cargo.lock"), "utf8");
  assert.equal(desktopVersion({ tauriConf: conf, cargoToml: toml }), "0.9.9-beta.4");
  // 锁文件里本应用那一条要跟上：`cargo fetch --locked` 会因为它不一致而失败。
  assert.match(lock, /name = "resume-pro-desktop"\r?\nversion = "0\.9\.9-beta\.4"/);

  applyVersion(root, before);
  for (const n of names) assert.equal(readFileSync(join(dir, n), "utf8"), original[n], n);
});
